name: ros2-talker-listener
version: '0.1'
summary: ROS 2 Talker/Listener Example using snaps’ content-sharing
description: |
  This example launches a ROS 2 talker and listener.
  The ROS 2 libraries are provided by a second snap through content-sharing.

confinement: devmode
base: core20

parts:
 ros-demos:
   plugin: colcon
   source: https://github.com/ros2/demos.git
   source-branch: foxy
   source-subdir: demo_nodes_cpp

apps:
 ros2-talker-listener:
   command: ros2 launch demo_nodes_cpp talker_listener.launch.py
   extensions: [ros2-foxy-ros-base]
