name: snap
on:
  push:
    branches:
      - content-sharing
  pull_request:
    branches:
      - content-sharing
  workflow_dispatch:
  workflow_call:

jobs:
  content-sharing-snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/build-install-test-snap.yaml@main
    with:
      branch-name: content-sharing
      snap-name: ros2-talker-listener
      snapcraft-args: --enable-experimental-extensions
      snap-install-args: --devmode
      test-script: |
                    #!/bin/bash
                    snap connect ros2-talker-listener:ros-foxy ros-foxy-ros-base

                    sudo snap install ros2-cli --channel=foxy/beta

                    check_node() {
                        local node_name=$1
                        ros2-cli.ros2 node list | grep -q "/$node_name"
                        if [ $? -eq 0 ]; then
                            echo "$node_name is running."
                        else
                            echo "Error - $node_name is not running."
                            exit 1
                        fi
                    }
                    check_topic() {
                        local topic_name=$1
                        local pub_count=$(ros2-cli.ros2 topic info /$topic_name | grep "Publisher count:" | awk '{print $3}')
                        local sub_count=$(ros2-cli.ros2 topic info /$topic_name | grep "Subscription count:" | awk '{print $3}')
                        if [ "$pub_count" -gt 0 ] && [ "$sub_count" -gt 0 ]; then
                            echo "$topic_name has publishers and subscribers."
                        else
                            echo "Error - $topic_name has no publishers or subscribers."
                            exit 1
                        fi
                    }

                    ros2-talker-listener &
                    pid=$!
                    check_node talker
                    check_node listener
                    check_topic chatter
                    kill $pid

                    echo "All checks passed successfully."
